---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    quadlet_user: ess-deploy
    quadlet_dir: "/home/ess-deploy/.config/containers/systemd"

  tasks:
    - name: Ensure quadlet directory exists
      file:
        path: "{{ quadlet_dir }}"
        state: directory
        owner: "{{ quadlet_user }}"
        group: "{{ quadlet_user }}"
        mode: "0755"
      become: true

    - name: Deploy quadlets
      copy:
        src: "../quadlets/"
        dest: "{{ quadlet_dir }}/"
        owner: "{{ quadlet_user }}"
        group: "{{ quadlet_user }}"
        mode: "0644"
      notify:
        - reload user systemd
        - restart quadlet services
      become: true

  handlers:
    - name: reload user systemd
      become_user: "{{ quadlet_user }}"
      become: true
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ lookup('ansible.builtin.pipe', 'id -u ' + quadlet_user) }}"
      command: systemctl --user daemon-reload

    - name: restart quadlet services
      become: true
      become_user: "{{ quadlet_user }}"
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ lookup('ansible.builtin.pipe', 'id -u ' + quadlet_user) }}"
      command: systemctl --user restart test-service-backend.service
